[build]
buildCommand = "composer install --optimize-autoloader --no-dev && npm install && npm run build"

[deploy]
startCommand = "bash -c 'php artisan serve --host=0.0.0.0 --port=${PORT} & php artisan reverb:start'"
